// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQaJlDfkoW5MDQa3JE9kzAuAdToxgIko',
    appId: '1:50447523338:web:0cdd09cb82d435cfcf09f3',
    messagingSenderId: '50447523338',
    projectId: 'aissms-transport',
    authDomain: 'aissms-transport.firebaseapp.com',
    storageBucket: 'aissms-transport.firebasestorage.app',
    measurementId: 'G-D637ZB7342',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3EIp2ST90BeyCZsM3z_IQX6bCgLNq61c',
    appId: '1:50447523338:android:139fab2497032ae1cf09f3',
    messagingSenderId: '50447523338',
    projectId: 'aissms-transport',
    storageBucket: 'aissms-transport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xJnGXBe060Lrfk-NcOzasqGi7NxABR8',
    appId: '1:50447523338:ios:7653180536c14955cf09f3',
    messagingSenderId: '50447523338',
    projectId: 'aissms-transport',
    storageBucket: 'aissms-transport.firebasestorage.app',
    iosBundleId: 'com.example.lastmileTransport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xJnGXBe060Lrfk-NcOzasqGi7NxABR8',
    appId: '1:50447523338:ios:7653180536c14955cf09f3',
    messagingSenderId: '50447523338',
    projectId: 'aissms-transport',
    storageBucket: 'aissms-transport.firebasestorage.app',
    iosBundleId: 'com.example.lastmileTransport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQaJlDfkoW5MDQa3JE9kzAuAdToxgIko',
    appId: '1:50447523338:web:249aaa1edc700508cf09f3',
    messagingSenderId: '50447523338',
    projectId: 'aissms-transport',
    authDomain: 'aissms-transport.firebaseapp.com',
    storageBucket: 'aissms-transport.firebasestorage.app',
    measurementId: 'G-BD44005DDF',
  );

}